fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    registration:
        confirmation:
            enabled: false
    from_email:
        address: 'admin@bk.ru'
        sender_name: 'admin'
    service:
        user_manager: sonata.user.orm.user_manager
        mailer: 'fos_user.mailer.noop'
    group:
        group_class:   App\Entity\UserGroup
        group_manager: sonata.user.orm.group_manager